services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80" # HTTP for Let's Encrypt challenge
      - "443:443" # HTTPS traffic served by Caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "8080"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    environment:
      - FASTAPI_ENV=development
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
