services:
  backend:
    build: ./backend
    ports:
      - "8080:8080" # Expose backend on port 8080
    volumes:
      - ./backend:/app
      - ./.env:/app/.env # Mount .env file from the root directory into the container
    environment:
      - FASTAPI_ENV=development # You can change this to suit your backend environment

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Expose frontend on port 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080 # Update to match backend port
      # This might need to be changed...
