version: '3.8'  # Ensure version is defined

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    environment:
      - FASTAPI_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=https://skid-msche-chatbot.us.reclaim.cloud/api
      - HOST=0.0.0.0
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt # Mount SSL certificates
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

